<?php
function lv_delivery_count($rows,$status){foreach($rows as $row)if($row['status']===$status)return (int)$row['total'];return 0;}
?>
<div class="row"><div class="col-12"><div class="card"><div class="card-body"><h4 class="page-title">Operational Quality</h4><p class="text-muted mb-0">Failures that can interrupt teaching, communication, assessment, or reporting.</p></div></div></div></div>
<div class="row">
<?php foreach(array('email'=>'Email','whatsapp'=>'WhatsApp') as $key=>$label):?><div class="col-md-3"><div class="card"><div class="card-body"><small><?php echo $label;?> failures · 7 days</small><h3 class="<?php echo lv_delivery_count($operations['delivery'][$key],'failed')?'text-danger':'';?>"><?php echo lv_delivery_count($operations['delivery'][$key],'failed');?></h3><span><?php echo lv_delivery_count($operations['delivery'][$key],'sent');?> sent</span></div></div></div><?php endforeach;?>
<div class="col-md-3"><div class="card"><div class="card-body"><small>Meeting link issues</small><h3 class="<?php echo $operations['meeting']['missing_links']?'text-warning':'';?>"><?php echo (int)$operations['meeting']['missing_links'];?></h3><span><?php echo (int)$operations['meeting']['open_incidents'];?> open incidents</span></div></div></div>
<div class="col-md-3"><div class="card"><div class="card-body"><small>Upload issues · 7 days</small><h3 class="<?php echo $operations['uploads']['rejected']?'text-danger':'';?>"><?php echo (int)$operations['uploads']['rejected'];?></h3><span><?php echo (int)$operations['uploads']['scanner_unavailable'];?> scanner unavailable</span></div></div></div>
</div>
<div class="row"><div class="col-xl-7"><div class="card"><div class="card-body"><h5>Background Jobs</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Job</th><th>Status</th><th>Processed</th><th>Failed</th><th>Completed</th></tr></thead><tbody><?php foreach($operations['job_runs'] as $run):?><tr><td><?php echo html_escape($run['job_key']);?></td><td><span class="badge badge-<?php echo $run['status']==='passed'?'success':($run['status']==='failed'?'danger':'warning');?>"><?php echo html_escape($run['status']);?></span></td><td><?php echo (int)$run['processed_count'];?></td><td><?php echo (int)$run['failure_count'];?></td><td><?php echo html_escape($run['completed_at']??'Running');?></td></tr><?php endforeach;?><?php if(!$operations['job_runs']):?><tr><td colspan="5" class="text-muted text-center">No recorded job runs yet.</td></tr><?php endif;?></tbody></table></div><p class="small text-muted mb-0">Additional failures: exports <?php echo (int)$operations['failed_exports'];?>, imports <?php echo (int)$operations['failed_imports'];?>, reminders <?php echo (int)$operations['failed_reminders'];?>.</p></div></div></div>
<div class="col-xl-5"><div class="card"><div class="card-body"><h5>Open Alerts</h5><?php foreach($operations['alerts'] as $alert):?><div class="alert alert-<?php echo $alert['severity']==='critical'?'danger':'warning';?> py-2"><strong><?php echo html_escape($alert['alert_key']);?></strong><br><?php echo html_escape($alert['message']);?><br><small><?php echo html_escape($alert['last_seen_at']);?></small></div><?php endforeach;?><?php if(!$operations['alerts']):?><div class="alert alert-success">No open operational alerts.</div><?php endif;?></div></div></div></div>
<div class="row"><div class="col-12"><div class="card"><div class="card-body"><h5>Provider Health History</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>Provider</th><th>Status</th><th>Response</th><th>Message</th><th>Checked</th></tr></thead><tbody><?php foreach($operations['provider_health'] as $row):?><tr><td><?php echo html_escape($row['provider_key']);?></td><td><?php echo html_escape($row['status']);?></td><td><?php echo $row['response_ms']!==null?(int)$row['response_ms'].' ms':'-';?></td><td><?php echo html_escape($row['message']);?></td><td><?php echo html_escape($row['checked_at']);?></td></tr><?php endforeach;?></tbody></table></div></div></div></div></div>
