<?php defined('BASEPATH') OR exit('No direct script access allowed');
$filter_options = $filter_options ?? array();
$exam_names = array_values(array_unique(array_filter(array_map(function($row){ return $row['name'] ?? ''; }, $filter_options['exam_names'] ?? array()))));
$sections_by_exam = array();
foreach (($filter_options['sub_categories'] ?? array()) as $row) { $examName = (string)($row['exam_name'] ?? ''); if (!isset($sections_by_exam[$examName])) $sections_by_exam[$examName] = array(); $sections_by_exam[$examName][] = (string)($row['name'] ?? ''); }
foreach ($sections_by_exam as &$items) $items = array_values(array_unique(array_filter($items))); unset($items);
?>
<style>
.exam-builder-wrap{font-family:Inter,Arial,sans-serif}.builder-hero{background:#f7fbff;border:1px solid #dbeafe;border-radius:18px;padding:18px}.soft-card{border:1px solid #e7edf5;border-radius:18px;box-shadow:0 8px 22px rgba(30,41,59,.06);background:#fff}.section-card{border:1px solid #dde7f3;border-radius:16px;background:#fbfdff;padding:16px;margin-bottom:14px}.metric{display:flex;justify-content:space-between;border-bottom:1px solid #eef2f7;padding:10px 0}.metric:last-child{border-bottom:0}.light-note{background:#f8fafc;border:1px solid #e2e8f0;border-radius:14px;padding:12px}.badge-soft{background:#eef6ff;color:#145388;border-radius:999px;padding:5px 10px;font-weight:700}.form-control{border-color:#d7e0ec}.btn-primary{background:#2f80ed;border-color:#2f80ed}.btn-success{background:#16a34a;border-color:#16a34a}.small-label{font-size:12px;text-transform:uppercase;letter-spacing:.04em;color:#64748b;font-weight:700}.sticky-summary{top:80px}.pool-count{font-weight:700;color:#145388}.pool-note{background:#f8fafc;border:1px dashed #cbd5e1;border-radius:12px;padding:10px}.exam-step{display:flex;align-items:center;margin-bottom:8px;color:#475569}.exam-step b{width:26px;height:26px;border-radius:50%;background:#eaf4ff;color:#145388;display:inline-flex;align-items:center;justify-content:center;margin-right:8px}
</style>
<div class="exam-builder-wrap">
<div class="builder-hero mb-3 d-flex justify-content-between align-items-start flex-wrap"><div><h4 class="page-title mb-1"><i class="mdi mdi-tune-variant title_icon"></i> <?php echo $exam?'Edit':'Create'; ?> Exam Pattern Builder</h4><p class="text-muted mb-0">Create a real exam pattern: sections, sectional timer, random question pool and student attempt rules.</p></div><a class="btn btn-light" href="<?php echo site_url('user/content_public_exams'); ?>">Back to Exams</a></div>
<form method="post" action="<?php echo site_url('user/exam_pattern_save/'.(int)($exam['id']??0)); ?>" id="patternForm">
<input type="hidden" name="workflow_action_token" value="<?php echo html_escape($workflow_action_token ?? ''); ?>">
<div class="row">
  <div class="col-xl-8">
    <div class="soft-card p-3 mb-3">
      <h4 class="header-title">Exam Details</h4>
      <div class="row">
        <div class="col-md-8 mb-2"><label>Exam Title</label><input class="form-control" name="title" required value="<?php echo html_escape($exam['title']??''); ?>" placeholder="Bank PO Pre Mock Test 1"></div>
        <div class="col-md-4 mb-2"><label>Exam Mode</label><select class="form-control" name="exam_mode"><option value="mock" <?php echo ($exam['exam_mode']??'mock')==='mock'?'selected':''; ?>>Mock Test</option><option value="real" <?php echo ($exam['exam_mode']??'')==='real'?'selected':''; ?>>Real Test</option><option value="practice" <?php echo ($exam['exam_mode']??'')==='practice'?'selected':''; ?>>Practice Test</option></select></div>
        <div class="col-md-4 mb-2"><label>Total Duration (minutes)</label><input class="form-control" type="number" min="1" name="time_limit_minutes" value="<?php echo (int)($exam['time_limit_minutes']??60); ?>" required></div>
        <div class="col-md-4 mb-2"><label>Passing Marks</label><input class="form-control" type="number" min="0" step="0.01" name="passing_marks" value="<?php echo html_escape($exam['passing_marks']??0); ?>"></div>
        <div class="col-md-4 mb-2"><label>Difficulty</label><select class="form-control" name="difficulty"><?php foreach(array('Beginner','Intermediate','Advanced') as $d): ?><option <?php echo ($exam['difficulty']??'Beginner')===$d?'selected':''; ?>><?php echo $d; ?></option><?php endforeach; ?></select></div>
        <div class="col-md-6 mb-2"><label>Availability Start</label><input class="form-control" type="datetime-local" name="starts_at" value="<?php echo !empty($exam['starts_at']) ? date('Y-m-d\TH:i', strtotime($exam['starts_at'])) : ''; ?>"></div>
        <div class="col-md-6 mb-2"><label>Availability End</label><input class="form-control" type="datetime-local" name="ends_at" value="<?php echo !empty($exam['ends_at']) ? date('Y-m-d\TH:i', strtotime($exam['ends_at'])) : ''; ?>"></div>
        <div class="col-md-12 mb-2"><label>Student Instructions</label><textarea class="form-control" rows="3" name="instructions" placeholder="Read all instructions carefully. Each section has its own timer."><?php echo html_escape($exam['instructions']??''); ?></textarea></div>
      </div>
      <div class="row mt-2">
        <div class="col-md-4"><label><input type="checkbox" name="randomize_questions" value="1" <?php echo !empty($exam['randomize_questions'])?'checked':''; ?>> Randomize question order</label></div>
        <div class="col-md-4"><label><input type="checkbox" name="shuffle_options" value="1" <?php echo !empty($exam['shuffle_options'])?'checked':''; ?>> Shuffle options</label></div>
        <div class="col-md-4"><label><input type="checkbox" name="show_result_immediately" value="1" <?php echo !empty($exam['show_result_immediately'])?'checked':''; ?>> Show result immediately</label></div>
        <div class="col-md-4"><label><input type="checkbox" name="show_correct_answers" value="1" <?php echo !empty($exam['show_correct_answers'])?'checked':''; ?>> Show correct answers</label></div>
        <div class="col-md-4"><label><input type="checkbox" name="show_explanations" value="1" <?php echo !empty($exam['show_explanations'])?'checked':''; ?>> Show explanations</label></div>
        <div class="col-md-4"><label><input type="checkbox" name="manual_moderation_required" value="1" <?php echo !empty($exam['manual_moderation_required'])?'checked':''; ?>> Manual review required</label></div>
        <div class="col-md-4 mt-2"><label>Max Attempts</label><input class="form-control" type="number" min="0" max="100" name="max_attempts" value="<?php echo (int)($exam['max_attempts']??1); ?>"><small class="text-muted">Use 1 for real test, 0 for unlimited.</small></div>
        <div class="col-md-4 mt-2"><label>Retake Wait (minutes)</label><input class="form-control" type="number" min="0" name="retake_wait_minutes" value="<?php echo (int)($exam['retake_wait_minutes']??0); ?>"></div>
        <div class="col-md-4 mt-2"><label>Workflow</label><select class="form-control" name="status"><option value="draft">Save Draft</option><option value="in_review">Submit for Review</option><option value="archived">Archive</option></select></div>
      </div>
    </div>

    <div class="soft-card p-3">
      <div class="d-flex justify-content-between align-items-center mb-2"><div><h4 class="header-title mb-0">Sections & Question Pools</h4><small class="text-muted">Example: Reasoning 35 questions from Reasoning Ability pool, 20 minutes.</small></div><button type="button" class="btn btn-sm btn-primary" id="addSection">+ Add Section</button></div>
      <div id="sectionsWrap"></div>
    </div>
  </div>
  <div class="col-xl-4"><div class="soft-card p-3 sticky-top sticky-summary"><h4 class="header-title">Pattern Summary</h4><div class="metric"><span>Sections</span><b id="summarySections">0</b></div><div class="metric"><span>Questions per attempt</span><b id="summaryQuestions">0</b></div><div class="metric"><span>Question pool</span><b id="summaryPool">0</b></div><div class="metric"><span>Total Marks</span><b id="summaryMarks">0</b></div><div class="metric"><span>Total Duration</span><b id="summaryDuration"><?php echo (int)($exam['time_limit_minutes']??60); ?> min</b></div><div class="metric"><span>Sectional Time</span><b id="summarySectionTime">0 min</b></div><div class="light-note mt-3"><div class="exam-step"><b>1</b>Create sections</div><div class="exam-step"><b>2</b>Select bank category</div><div class="exam-step"><b>3</b>Enter questions per attempt</div><div class="exam-step"><b>4</b>Every attempt gets random questions</div></div><button class="btn btn-success btn-block mt-3">Save Exam Pattern</button></div></div>
</div>
</form>
</div>
<script>
var poolEndpoint = '<?php echo site_url('user/question_bank_pool'); ?>';
var sectionsByExam = <?php echo json_encode($sections_by_exam); ?>;
var examNames = <?php echo json_encode(array_values($exam_names)); ?>;
var existingSections = <?php echo json_encode(array_map(function($s){return array('title'=>$s['title']??'','instructions'=>$s['instructions']??'','default_marks'=>$s['default_marks']??1,'default_negative_marks'=>$s['default_negative_marks']??0,'section_time_minutes'=>$s['section_time_minutes']??0,'source_exam_type'=>$s['source_exam_type']??'','source_topic'=>$s['source_section']??'','source_difficulty'=>$s['source_difficulty']??'','random_count'=>$s['selection_count']??$s['question_count']??0);}, $sections)); ?>;
function esc(s){return String(s||'').replace(/[&<>'"]/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
function optionHtml(value,label,selected){return '<option value="'+esc(value)+'" '+(selected?'selected':'')+'>'+esc(label||value)+'</option>';}
function examSelectHtml(index, selected){var html='<select class="form-control source-exam" name="sections['+index+'][source_exam_type]" required><option value="">Select Exam Name</option>'; examNames.forEach(function(name){html+=optionHtml(name,name,selected===name);}); return html+'</select>';}
function sectionSelectHtml(index, exam, selected){var list=sectionsByExam[exam||'']||[]; var html='<select class="form-control source-topic" name="sections['+index+'][source_topic]" required><option value="">Select Sub Category / Section</option>'; list.forEach(function(name){html+=optionHtml(name,name,selected===name);}); return html+'</select>';}
function refreshSectionSelect(card){var idx=Array.prototype.indexOf.call(document.querySelectorAll('[data-section]'),card); var old=card.querySelector('.source-topic'); var selected=old ? old.value : ''; var exam=card.querySelector('.source-exam') ? card.querySelector('.source-exam').value : ''; card.querySelector('.source-topic-wrap').innerHTML=sectionSelectHtml(idx, exam, selected);}
function renderOptions(card){var exam=card.querySelector('.source-exam').value.trim(), topic=card.querySelector('.source-topic').value.trim(), diff=card.querySelector('.source-difficulty').value.trim(); card.querySelector('.available-count').textContent='Loading pool...'; var url=poolEndpoint+'?exam='+encodeURIComponent(exam)+'&topic='+encodeURIComponent(topic)+'&difficulty='+encodeURIComponent(diff); fetch(url,{credentials:'same-origin'}).then(function(r){return r.json();}).then(function(data){var total=parseInt(data.total||0,10); card.querySelector('.available-count').textContent=total+' active question(s) available'; card.querySelector('.pool-hidden').value=total; updateSummary();}).catch(function(){card.querySelector('.available-count').textContent='Could not load question pool. Check filters and retry.';});}
function sectionTemplate(index, data){data=data||{}; var html='<div class="section-card" data-section><div class="d-flex justify-content-between"><div><h5>Section '+(index+1)+'</h5><span class="badge-soft">Random question pool</span></div><button type="button" class="btn btn-sm btn-outline-danger remove-section">Remove</button></div>'+ '<div class="row mt-2"><div class="col-md-4 mb-2"><label>Section Title</label><input class="form-control section-title-input" name="sections['+index+'][title]" required value="'+esc(data.title||'')+'" placeholder="Reasoning Ability"></div><div class="col-md-2 mb-2"><label>Questions</label><input class="form-control random-count" type="number" min="1" name="sections['+index+'][random_count]" value="'+esc(data.random_count||0)+'" required></div><div class="col-md-2 mb-2"><label>Section Time</label><input class="form-control section-time" type="number" min="0" name="sections['+index+'][section_time_minutes]" value="'+esc(data.section_time_minutes||0)+'"></div><div class="col-md-2 mb-2"><label>Marks</label><input class="form-control default-marks" type="number" min="0.01" step="0.01" name="sections['+index+'][default_marks]" value="'+esc(data.default_marks||1)+'"></div><div class="col-md-2 mb-2"><label>Negative</label><input class="form-control" type="number" min="0" step="0.01" name="sections['+index+'][default_negative_marks]" value="'+esc(data.default_negative_marks||0)+'"></div>'+ '<div class="col-md-4 mb-2"><label>Question Bank Exam</label>'+examSelectHtml(index, data.source_exam_type||'')+'</div><div class="col-md-4 mb-2"><label>Question Bank Category / Section</label><div class="source-topic-wrap">'+sectionSelectHtml(index, data.source_exam_type||'', data.source_topic||'')+'</div></div><div class="col-md-4 mb-2"><label>Difficulty</label><select class="form-control source-difficulty" name="sections['+index+'][source_difficulty]"><option value="">Any</option><option '+(data.source_difficulty==='Beginner'?'selected':'')+'>Beginner</option><option '+(data.source_difficulty==='Intermediate'?'selected':'')+'>Intermediate</option><option '+(data.source_difficulty==='Advanced'?'selected':'')+'>Advanced</option></select><input type="hidden" name="sections['+index+'][selection_mode]" value="random_pool"></div>'+ '<div class="col-md-12 mb-2"><div class="pool-note"><button type="button" class="btn btn-sm btn-outline-primary apply-pool">Refresh Available Count</button> <span class="available-count pool-count ml-2"></span><input type="hidden" class="pool-hidden" value="0"><small class="d-block text-muted mt-1">Every attempt randomly draws the requested number of questions from this active Question Bank pool. Manual question selection is disabled.</small></div></div></div></div>'; return {html:html};}
function reindex(){Array.prototype.forEach.call(document.querySelectorAll('[data-section]'),function(card,i){card.querySelector('h5').textContent='Section '+(i+1); Array.prototype.forEach.call(card.querySelectorAll('[name]'),function(el){el.name=el.name.replace(/sections\[\d+\]/,'sections['+i+']');});});}
function addSection(data){var idx=document.querySelectorAll('[data-section]').length; var t=sectionTemplate(idx,data||{}); var wrap=document.getElementById('sectionsWrap'); wrap.insertAdjacentHTML('beforeend',t.html); var card=wrap.lastElementChild; renderOptions(card);}
function updateSummary(){var sections=document.querySelectorAll('[data-section]'),q=0,m=0,pool=0,stime=0; Array.prototype.forEach.call(sections,function(card){var count=parseInt(card.querySelector('.random-count').value||'0',10); var marks=parseFloat(card.querySelector('.default-marks').value||'1'); var available=parseInt(card.querySelector('.pool-hidden').value||'0',10); q+=count; m+=count*marks; pool+=available; stime+=parseInt(card.querySelector('.section-time').value||'0',10);}); document.getElementById('summarySections').textContent=sections.length; document.getElementById('summaryQuestions').textContent=q; document.getElementById('summaryMarks').textContent=m.toFixed(2); document.getElementById('summaryPool').textContent=pool; document.getElementById('summarySectionTime').textContent=stime+' min';}
document.getElementById('addSection').addEventListener('click',function(){addSection({title:''});});
document.getElementById('sectionsWrap').addEventListener('click',function(e){var card=e.target.closest('[data-section]'); if(!card)return; if(e.target.classList.contains('remove-section')){card.remove(); reindex(); updateSummary();} if(e.target.classList.contains('apply-pool')){renderOptions(card);}});
document.getElementById('sectionsWrap').addEventListener('change',function(e){var card=e.target.closest('[data-section]'); if(!card)return; if(e.target.classList.contains('source-exam')) { refreshSectionSelect(card); renderOptions(card); } else if(e.target.classList.contains('source-topic')||e.target.classList.contains('source-difficulty')) renderOptions(card); updateSummary();});
document.getElementById('sectionsWrap').addEventListener('input', updateSummary);
if(existingSections.length){existingSections.forEach(addSection);}else{addSection({title:'Reasoning Ability', random_count:35, section_time_minutes:20}); addSection({title:'Quantitative Aptitude', random_count:35, section_time_minutes:20}); addSection({title:'English Language', random_count:30, section_time_minutes:20});} updateSummary();
document.querySelector('input[name="time_limit_minutes"]').addEventListener('input', function(){ document.getElementById('summaryDuration').textContent=(this.value||0)+' min'; });
</script>
